//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnicalTestNewShore.WebServices.Data.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ResultsConnection : DbContext
    {
        public ResultsConnection()
            : base("name=ResultsConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<REGISTERED> REGISTERED { get; set; }
        public virtual DbSet<RESULT> RESULT { get; set; }
        public virtual DbSet<CONTENT> CONTENT { get; set; }
    }
}
